services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Vinayagarrr
      DATABASE_PORT: 5432
      DATABASE_HOSTNAME: postgres
      SECRET_KEY: we4567890plkmnbvcde456789iokjhgtyuik345678ijhb
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Vinayagarrr
      POSTGRES_DB: fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
